/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ftreadertest_Tpcsc */

#ifndef _Included_com_example_ftreadertest_Tpcsc
#define _Included_com_example_ftreadertest_Tpcsc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ftreadertest_Tpcsc
 * Method:    testA
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_ftreadertest_Tpcsc_testA
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
