/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ftReaderStandard_Tpcsc */

#ifndef _Included_com_example_ftReaderStandard_Tpcsc
#define _Included_com_example_ftReaderStandard_Tpcsc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ftReaderStandard_Tpcsc
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_ftReaderStandard_Tpcsc_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_ftReaderStandard_Tpcsc
 * Method:    SCardEstablishContext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_ftReaderStandard_Tpcsc_SCardEstablishContext
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ftReaderStandard_Tpcsc
 * Method:    SCardListReaders
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ftReaderStandard_Tpcsc_SCardListReaders
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ftReaderStandard_Tpcsc
 * Method:    SCardConnect
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_ftReaderStandard_Tpcsc_SCardConnect
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_ftReaderStandard_Tpcsc
 * Method:    SCardStatus
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_ftReaderStandard_Tpcsc_SCardStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ftReaderStandard_Tpcsc
 * Method:    SCardTransmit
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_ftReaderStandard_Tpcsc_SCardTransmit
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_example_ftReaderStandard_Tpcsc
 * Method:    SCardControl
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_ftReaderStandard_Tpcsc_SCardControl
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_example_ftReaderStandard_Tpcsc
 * Method:    SCardDisconnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_ftReaderStandard_Tpcsc_SCardDisconnect
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ftReaderStandard_Tpcsc
 * Method:    SCardReleaseContext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_ftReaderStandard_Tpcsc_SCardReleaseContext
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ftReaderStandard_Tpcsc
 * Method:    SCardIsValidContext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_ftReaderStandard_Tpcsc_SCardIsValidContext
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ftReaderStandard_Tpcsc
 * Method:    SCardGetStatusChange
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_ftReaderStandard_Tpcsc_SCardGetStatusChange
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_ftReaderStandard_Tpcsc
 * Method:    SCardGetLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ftReaderStandard_Tpcsc_SCardGetLastError
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
