/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ftreadertest_Tpcsc */

#ifndef _Included_com_example_ftreadertest_Tpcsc
#define _Included_com_example_ftreadertest_Tpcsc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ftreadertest_Tpcsc
 * Method:    testA
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_ftreadertest_Tpcsc_testA
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_ftreadertest_Tpcsc
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_ftreadertest_Tpcsc_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_ftreadertest_Tpcsc
 * Method:    SCardEstablishContext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_ftreadertest_Tpcsc_SCardEstablishContext
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ftreadertest_Tpcsc
 * Method:    SCardListReaders
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ftreadertest_Tpcsc_SCardListReaders
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ftreadertest_Tpcsc
 * Method:    SCardConnect
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_ftreadertest_Tpcsc_SCardConnect
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_ftreadertest_Tpcsc
 * Method:    SCardStatus
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_ftreadertest_Tpcsc_SCardStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ftreadertest_Tpcsc
 * Method:    SCardTransmit
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_ftreadertest_Tpcsc_SCardTransmit
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_example_ftreadertest_Tpcsc
 * Method:    SCardDisconnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_ftreadertest_Tpcsc_SCardDisconnect
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ftreadertest_Tpcsc
 * Method:    SCardReleaseContext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_ftreadertest_Tpcsc_SCardReleaseContext
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ftreadertest_Tpcsc
 * Method:    DUKPTSetEncMode
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_example_ftreadertest_Tpcsc_DUKPTSetEncMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_ftreadertest_Tpcsc
 * Method:    DUKPTSetIPEKKSN
 * Signature: ([BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_example_ftreadertest_Tpcsc_DUKPTSetIPEKKSN
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_example_ftreadertest_Tpcsc
 * Method:    DUKPTGetKSN
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_ftreadertest_Tpcsc_DUKPTGetKSN
  (JNIEnv *, jobject);
  
/*
 * Class:     com_example_ftreadertest_Tpcsc
 * Method:    DUKPTTransmit
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_ftreadertest_Tpcsc_DUKPTTransmit
  (JNIEnv *, jobject,jbyteArray, jint,jbyteArray, jint, jint);  
  
  

#ifdef __cplusplus
}
#endif
#endif
